# Generated by Django 4.2.7 on 2023-11-27 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_useraccount_is_staff"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizerprofile",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
